name: homl3
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - adwaita-icon-theme=48.1=unix_1
  - anyio=4.10.0=pyhe01879c_0
  - aom=3.9.1=hf036a51_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h1b7cace_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - atk-1.0=2.38.0=h4bec284_2
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.5=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - box2d-py=2.3.8=py310h79c4529_10
  - brotli=1.1.0=h1c43f85_4
  - brotli-bin=1.1.0=h1c43f85_4
  - brotli-python=1.1.0=py310h79c4529_4
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h950ec3b_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py310h137ab04_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hf166250_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h0dc2134_0
  - debugpy=1.8.16=py310h31e056b_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - epoxy=1.5.10=h5eb16cf_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=6.1.2=gpl_h9c046ae_106
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.2=py310h929a2ac_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.0=h694c41f_1
  - fribidi=1.0.16=h8616949_0
  - gdk-pixbuf=2.44.1=h07555a4_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glib-tools=2.86.0=h8650975_0
  - gmp=6.3.0=hf036a51_2
  - graphite2=1.3.14=h21dd04a_2
  - graphviz=13.1.2=h42bfd48_0
  - gtk3=3.24.43=h70b172e_5
  - gts=0.7.6=h53e17e3_4
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.5.0=hc5d3ef4_0
  - hicolor-icon-theme=0.17=h694c41f_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.17.2=pyh31c8845_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - iqtree=3.0.1=h6ed3961_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310h2ec42d9_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter-server-mathjax=0.2.6=pyhbbac1ac_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py310hfcdb090_1
  - krb5=1.21.3=h37d8d59_0
  - lame=3.100=hb7f2c08_1003
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20240722.0=cxx17_h0e468a2_4
  - libass=0.17.3=hcafd6c1_2
  - libblas=3.9.0=20_osx64_openblas
  - libbrotlicommon=1.1.0=h1c43f85_4
  - libbrotlidec=1.1.0=h1c43f85_4
  - libbrotlienc=1.1.0=h1c43f85_4
  - libcblas=3.9.0=20_osx64_openblas
  - libcxx=21.1.1=h3d58e20_0
  - libdeflate=1.24=hcc1b750_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.4.6=h281671d_1
  - libfreetype=2.14.0=h694c41f_1
  - libfreetype6=2.14.0=h6912278_1
  - libgd=2.3.3=h8555400_11
  - libgfortran=15.1.0=h5f6db21_1
  - libgfortran5=15.1.0=hfa3c126_1
  - libglib=2.86.0=h7cafd41_0
  - libhwloc=2.12.1=default_h8c32e24_1000
  - libiconv=1.18=h57a12c2_2
  - libintl=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.0=h6e16a3a_0
  - liblapack=3.9.0=20_osx64_openblas
  - liblzma=5.8.1=hd471939_2
  - liblzma-devel=5.8.1=hd471939_2
  - libopenblas=0.3.25=openmp_hfef2a42_0
  - libopenvino=2024.4.0=h84cb933_2
  - libopenvino-auto-batch-plugin=2024.4.0=h92dab7a_2
  - libopenvino-auto-plugin=2024.4.0=h92dab7a_2
  - libopenvino-hetero-plugin=2024.4.0=h14156cc_2
  - libopenvino-intel-cpu-plugin=2024.4.0=h84cb933_2
  - libopenvino-ir-frontend=2024.4.0=h14156cc_2
  - libopenvino-onnx-frontend=2024.4.0=he28f95a_2
  - libopenvino-paddle-frontend=2024.4.0=he28f95a_2
  - libopenvino-pytorch-frontend=2024.4.0=hc3d39de_2
  - libopenvino-tensorflow-frontend=2024.4.0=h488aad4_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=hc3d39de_2
  - libopus=1.5.2=he3325bb_0
  - libpng=1.6.50=h84aeda2_1
  - libprotobuf=5.28.2=h8b30cf6_0
  - librsvg=2.58.4=h21a6cfa_3
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.50.4=h39a8b3b_0
  - libtiff=4.7.0=h59ddb5d_6
  - libvpx=1.14.1=hf036a51_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.15=hb7f2c08_0
  - libxgboost=1.7.6=cpu_h2b4cd7c_6
  - libxml2=2.13.8=he1bc88e_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.0=hf4e0ed4_0
  - markupsafe=3.0.2=py310h8e2f543_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbdime=3.2.1=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nltk=3.8.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numexpr=2.8.8=py310h276d7da_0
  - numpy=1.26.4=py310h4bfa8fc_0
  - openh264=2.4.1=h73e2aa4_0
  - openjpeg=2.5.3=h036ada5_1
  - openssl=3.5.4=h230baf5_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h6ef8af8_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=ha3e7e28_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.1.0=py310he65384d_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=ha059160_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.0.0=py310h1b7cace_1
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.14=he965462_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=1.7.6=cpu_py310h86d5599_6
  - pycparser=2.22=pyh29332c3_1
  - pydot=1.4.2=py310h2ec42d9_4
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=11.1=py310h89b807b_1
  - pyobjc-framework-cocoa=11.1=py310h06ed557_1
  - pyparsing=3.2.4=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=h93e8a92_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h8e2f543_2
  - pyzmq=27.1.0=py310hbbd5e6a_0
  - readline=8.2=h7cca4af_2
  - referencing=0.36.2=pyh29332c3_0
  - regex=2025.9.1=py310hd2d5e8d_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.1=py310h80fed0c_1
  - scipy=1.11.4=py310h3f1db6d_0
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h25c286d_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py310hc2764c8_0
  - svt-av1=2.3.0=h97d8b74_0
  - tbb=2022.2.0=hc025b3e_1
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=hf689a15_2
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py310h1b7cace_1
  - tqdm=4.66.6=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310h1b7cace_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - x264=1!164.3095=h775f41a_2
  - x265=3.5=hbb4e6a2_3
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - xz=5.8.1=h357f2ed_2
  - xz-gpl-tools=5.8.1=h357f2ed_2
  - xz-tools=5.8.1=hd471939_2
  - yaml=0.2.5=h4132b18_3
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py310h3aa7efa_0
  - zstd=1.5.7=h8210216_2
  - pip:
      - absl-py==2.3.1
      - ale-py==0.11.2
      - anndata==0.11.4
      - array-api-compat==1.12.0
      - astunparse==1.6.3
      - biopython==1.86
      - cachetools==5.5.2
      - cloudpickle==3.1.1
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - einops==0.8.1
      - etils==1.13.0
      - farama-notifications==0.0.4
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fsspec==2025.9.0
      - gast==0.6.0
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - google-cloud-aiplatform==1.36.4
      - google-cloud-bigquery==3.37.0
      - google-cloud-core==2.4.3
      - google-cloud-resource-manager==1.14.2
      - google-cloud-storage==2.13.0
      - google-crc32c==1.7.1
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpc-google-iam-v1==0.14.2
      - grpcio==1.74.0
      - grpcio-status==1.62.3
      - gviz-api==1.10.0
      - gymnasium==1.2.0
      - h5py==3.14.0
      - hf-xet==1.1.10
      - huggingface-hub==0.34.5
      - immutabledict==4.2.1
      - keras==2.14.0
      - keras-core==0.1.7
      - keras-tuner==1.4.7
      - kt-legacy==1.0.5
      - legacy-api-wrap==1.5
      - libclang==18.1.1
      - llvmlite==0.45.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - namex==0.1.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.62.1
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - pandas==2.2.3
      - promise==2.3
      - proto-plus==1.26.1
      - protobuf==4.21.12
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pygame==2.6.1
      - pynndescent==0.5.13
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scanpy==1.11.5
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - session-info2==0.2.3
      - shapely==2.1.1
      - simple-parsing==0.1.7
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-profile==2.14.0
      - tensorflow==2.14.1
      - tensorflow-datasets==4.9.9
      - tensorflow-estimator==2.14.0
      - tensorflow-hub==0.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - tensorflow-serving-api==2.14.1
      - termcolor==3.1.0
      - tokenizers==0.15.2
      - toml==0.10.2
      - transformers==4.35.2
      - treetime==2025.2
      - typing-extensions==4.12.2
      - umap-learn==0.5.9.post2
      - upsetplot==0.9.0
      - uritools==5.0.0
      - urlextract==1.8.0
      - werkzeug==3.1.3
      - wrapt==1.14.2
prefix: /Users/mora.toneguzzo/miniconda/envs/homl3
